[package]
name = "todo-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ncurses = "5.101.0"
libc = "0.2.97"
image = "0.24.6"
imageproc = "0.23.0"
rusttype = "0.9.3"
